CREATE TABLE candidate_pool_history
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date          date                                    NOT NULL,
    strategy      VARCHAR(30)                             NOT NULL,
    market        VARCHAR(10)                             NOT NULL,
    stk_cd        VARCHAR(20)                             NOT NULL,
    stk_nm        VARCHAR(100),
    pool_score    DECIMAL(5, 2),
    appear_count  INTEGER,
    first_seen    TIMESTAMP WITHOUT TIME ZONE,
    last_seen     TIMESTAMP WITHOUT TIME ZONE,
    led_to_signal BOOLEAN,
    signal_id     BIGINT,
    CONSTRAINT pk_candidate_pool_history PRIMARY KEY (id)
);

CREATE TABLE market_daily_context
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date                  date                                    NOT NULL,
    kospi_open            DECIMAL(8, 2),
    kospi_close           DECIMAL(8, 2),
    kospi_change_pct      DECIMAL(6, 3),
    kospi_volume          BIGINT,
    kosdaq_open           DECIMAL(8, 2),
    kosdaq_close          DECIMAL(8, 2),
    kosdaq_change_pct     DECIMAL(6, 3),
    kosdaq_volume         BIGINT,
    advancing_stocks      INTEGER,
    declining_stocks      INTEGER,
    unchanged_stocks      INTEGER,
    advance_decline_ratio DECIMAL(6, 3),
    frgn_net_buy_kospi    DECIMAL(14),
    inst_net_buy_kospi    DECIMAL(14),
    frgn_net_buy_kosdaq   DECIMAL(14),
    inst_net_buy_kosdaq   DECIMAL(14),
    news_sentiment        VARCHAR(20),
    news_trading_ctrl     VARCHAR(20),
    vix_equivalent        DECIMAL(6, 2),
    economic_event_today  BOOLEAN,
    economic_event_nm     VARCHAR(200),
    total_signals_today   INTEGER,
    signal_win_rate_today DECIMAL(5, 2),
    avg_pnl_pct_today     DECIMAL(7, 4),
    recorded_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_market_daily_context PRIMARY KEY (id)
);

CREATE TABLE overnight_evaluations
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    signal_id            BIGINT,
    position_id          BIGINT,
    stk_cd               VARCHAR(20)                             NOT NULL,
    strategy             VARCHAR(30),
    java_overnight_score DECIMAL(5, 2),
    final_score          DECIMAL(5, 2),
    verdict              VARCHAR(20),
    confidence           VARCHAR(10),
    reason               VARCHAR(255),
    pnl_pct              DECIMAL(7, 4),
    flu_rt               DECIMAL(7, 4),
    cntr_strength        DECIMAL(7, 2),
    rsi14                DECIMAL(5, 2),
    ma_alignment         VARCHAR(30),
    bid_ratio            DECIMAL(6, 3),
    entry_price          DECIMAL(10),
    cur_prc_at_eval      DECIMAL(10),
    score_components     JSONB,
    next_day_open        DECIMAL(10),
    next_day_pnl_pct     DECIMAL(7, 4),
    verdict_correct      BOOLEAN,
    evaluated_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_overnight_evaluations PRIMARY KEY (id)
);

CREATE TABLE risk_events
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_type      VARCHAR(30)                             NOT NULL,
    stk_cd          VARCHAR(20),
    strategy        VARCHAR(30),
    signal_id       BIGINT,
    threshold_value DECIMAL(10, 2),
    actual_value    DECIMAL(10, 2),
    description     VARCHAR(255),
    action_taken    VARCHAR(100),
    occurred_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_risk_events PRIMARY KEY (id)
);

CREATE TABLE stock_master
(
    stk_cd          VARCHAR(20)  NOT NULL,
    stk_nm          VARCHAR(100) NOT NULL,
    market          VARCHAR(10),
    sector          VARCHAR(50),
    industry        VARCHAR(50),
    listed_at       date,
    par_value       INTEGER,
    listed_shares   BIGINT,
    is_active       BOOLEAN,
    last_price      DECIMAL(10),
    last_price_date date,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_stock_master PRIMARY KEY (stk_cd)
);

CREATE TABLE strategy_daily_stats
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date                date                                    NOT NULL,
    strategy            VARCHAR(30)                             NOT NULL,
    total_signals       INTEGER,
    enter_count         INTEGER,
    cancel_count        INTEGER,
    skip_entry_count    INTEGER,
    tp1_hit_count       INTEGER,
    tp2_hit_count       INTEGER,
    sl_hit_count        INTEGER,
    force_close_count   INTEGER,
    expired_count       INTEGER,
    overnight_count     INTEGER,
    win_rate            DECIMAL(5, 2),
    avg_rule_score      DECIMAL(5, 2),
    avg_ai_score        DECIMAL(5, 2),
    avg_rr_ratio        DECIMAL(5, 2),
    pct_above_threshold DECIMAL(5, 2),
    avg_pnl_pct         DECIMAL(7, 4),
    total_pnl_abs       DECIMAL(14),
    avg_hold_min        DECIMAL(7, 1),
    best_pnl_pct        DECIMAL(7, 4),
    worst_pnl_pct       DECIMAL(7, 4),
    threshold_snapshot  DECIMAL(5, 2),
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_strategy_daily_stats PRIMARY KEY (id)
);

CREATE TABLE strategy_param_history
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    strategy   VARCHAR(30)                             NOT NULL,
    param_name VARCHAR(50)                             NOT NULL,
    old_value  VARCHAR(100),
    new_value  VARCHAR(100)                            NOT NULL,
    changed_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    changed_by VARCHAR(50),
    reason     VARCHAR(255),
    CONSTRAINT pk_strategy_param_history PRIMARY KEY (id)
);

ALTER TABLE open_positions
    ADD CONSTRAINT uc_open_positions_signal UNIQUE (signal_id);

ALTER TABLE market_daily_context
    ADD CONSTRAINT uq_mdc_date UNIQUE (date);

ALTER TABLE strategy_daily_stats
    ADD CONSTRAINT uq_sds_date_strategy UNIQUE (date, strategy);

CREATE INDEX idx_di_date_stk ON daily_indicators (date DESC, stk_cd);

CREATE INDEX idx_mdc_date ON market_daily_context (date DESC);

CREATE INDEX idx_oe_position_id ON overnight_evaluations (position_id);

CREATE INDEX idx_oe_signal_id ON overnight_evaluations (signal_id);

CREATE INDEX idx_oe_stk_cd ON overnight_evaluations (stk_cd, evaluated_at DESC);

CREATE INDEX idx_oe_verdict ON overnight_evaluations (verdict, evaluated_at DESC);

CREATE INDEX idx_re_date ON risk_events (occurred_at DESC);

CREATE INDEX idx_re_type_date ON risk_events (event_type, occurred_at DESC);

CREATE INDEX idx_sds_date ON strategy_daily_stats (date DESC);

CREATE INDEX idx_sds_strategy ON strategy_daily_stats (strategy, date DESC);

CREATE INDEX idx_sm_market ON stock_master (market);

CREATE INDEX idx_sm_sector ON stock_master (sector);

CREATE INDEX idx_sph_strategy ON strategy_param_history (strategy, changed_at DESC);

DROP TABLE kiwoom_token CASCADE;

ALTER TABLE signal_score_components
    ALTER COLUMN computed_at DROP NOT NULL;

ALTER TABLE portfolio_config
    ALTER COLUMN enabled_strategies DROP NOT NULL;
